[package]
name = "grrs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
anyhow = "1.0.102"

[dev-dependencies]
assert_cmd = "2.1.2"
predicates = "3.1.4"
assert_fs = "1.1.3"
